app <- ShinyDriver$new("CREDnf")
app$snapshotInit("Domain4-7")

app$setInputs(title = "Manuscript for testing")
app$setInputs(author = "Harry Potter")
app$setInputs(email = "hpotter@hogwarts.co.uk")
app$setInputs(checklist4b = "Yes")
app$setInputs(response4b = "We used a thorough and justified reinforcement schedule", allowInputNoBinding_ = TRUE)
app$setInputs(checklist4d = "Yes")
app$setInputs(response4d = "Lots of brain activity variables like blood flow and neuronal activity", allowInputNoBinding_ = TRUE)
app$setInputs(checklist4e = "Yes")
app$setInputs(response4e = "We used the CRED-nf checklist for reporting our study", allowInputNoBinding_ = TRUE)
app$setInputs(checklist5b = "Partially")
app$setInputs(response5b = "This is only a partial explanation", allowInputNoBinding_ = TRUE)
app$setInputs(checklist5c = "Not applicable, there was only one participant group")
app$setInputs(checklist6a = "Not applicable, the study does not take cognitive or behavioural measures")
app$setInputs(checklist6b = "Yes")
app$setInputs(response6b = "We compared regulation success thoroughly", allowInputNoBinding_ = TRUE)
app$setInputs(checklist7a = "Yes")
app$setInputs(response7a = "All material are open access because it's the best", allowInputNoBinding_ = TRUE)
app$snapshot()
