app <- ShinyDriver$new("CREDnf")
app$snapshotInit("Domain1-3")

app$setInputs(title = "Test Manuscript")
app$setInputs(author = "Ronald Macdonald")
app$setInputs(email = "rmaccyd@macdonalds.com")
app$snapshot()
app$setInputs(checklist1b = "Yes")
app$setInputs(response1b = "This is my sampling plan and sample size", allowInputNoBinding_ = TRUE)
app$setInputs(checklist1a = "Yes")
app$setInputs(checklist1a = "No")
app$setInputs(checklist1a = "Yes")
app$setInputs(response1a = "I want to delete this later", allowInputNoBinding_ = TRUE)
app$snapshot()
app$setInputs(checklist2b = "Yes, but a double-blind was not used")
app$setInputs(`checklist2c.rater` = "Not applicable, there was only one participant group")
app$setInputs(`checklist2c.stat` = "Not applicable, there was only one participant group")
app$setInputs(checklist2d = "Yes")
app$setInputs(response2d = "Many measures were taken", allowInputNoBinding_ = TRUE)
app$setInputs(checklist2e = "Yes, and a standard-of-care intervention group was not used as a benchmark for improvement")
app$snapshot()
app$setInputs(checklist3a = "Yes")
app$setInputs(response3a = "Psychosocial data were collected", allowInputNoBinding_ = TRUE)
app$setInputs(checklist3c = "Yes")
app$setInputs(response3c = "We used very complex strategies for participants", allowInputNoBinding_ = TRUE)
app$setInputs(checklist3e = "Yes")
app$setInputs(checklist3e = "No")
app$snapshot()
