---
title: "NF/BCI Instructions Checklist"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
classoption: landscape
geometry: "left=1cm,right=1cm,top=1cm,bottom=2cm"
header-includes:
- \usepackage{fancyhdr}
- \usepackage{longtable}
- \usepackage{array}
- \fancyhf{}
- \renewcommand{\headrulewidth}{0pt}
- \fancyfoot[C]{\itshape{This report has been generated using the NF-BCI-instructions-checklist online checklist version 1.0, adapted from the NF-BCI-instructions-checklist manuscript which is freely available here https://doi.org/10.1093/brain/awaa009.}}
- \fancyhead[R]{\thepage}
- \pagestyle{fancy}
- \fancypagestyle{plain}{\pagestyle{fancy}}
params:
  title: NA
  author: NA
  email: NA
  domains: NA
  checkIDs: NA
  checkItem: NA
  response: NA
  ticks: NA
  boilers: NA
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(data.table)
library(kableExtra)
library(knitr)
library(dplyr)
library(stringr)

escapestr <- function(x) {
  x <- gsub("\\,", "\\\\,", x)
  x <- gsub("\\.", "\\\\.", x)
  x <- gsub("\\(", "\\\\(", x)
  x <- gsub("\\)", "\\\\)", x)
  x <- gsub("\\/", "\\\\/", x)
  x <- gsub("\\?", "\\\\?", x)
  x <- gsub("\\-", "\\\\-", x)
  x <- gsub("\\:", "\\\\:", x)
  return(x)
}

newlineMd <- function(str){
    return(str_replace_all(str, ", ", "  \n"))
}

newline <- function(str){
    return(str_replace_all(str, ", ", "\n"))
}

newlineHtml <- function(str){
    return(str_replace_all(str, ", ", "<br>"))
}

```

```{r, echo=FALSE}
# Create a table
table.dt <- data.table("Item.num" = params$checkIDs, "Checklist.item" = params$checkItem, "Instructions.type" = linebreak(newline(params$ticks)), "Manuscript.details"=params$response)

```


```{r}
# Modify Elements
# one instruction perlines
#set(table.dt, "Instructions.type" = "Instructions.type", value = str_replace(table.dt[[j]],", ","\n"))
#table.dt[,(Instructions.type):= str_replace(table.dt[,..Instructions.type],", ","\n")]
```


```{r}
escboil <- escapestr(params$response)
# Check for matches with boilerplate
boilmatch <- as.logical(sapply(escboil, function(x) {any(grepl(x, params$boilers))}))
```


**Manuscript title:** `r params$title`  
**Corresponding Author:** `r params$author`  
**Corresponding author email:** `r params$email`  
&nbsp;

\renewcommand{\arraystretch}{1.5}
```{r}
hdr <- c("Item", "Checklist item", "Instructions type", "Manuscript Details")

table.dt %>%
  mutate(Manuscript.details = cell_spec(Manuscript.details, italic=boilmatch)) %>%
  select(Item.num, Checklist.item, Instructions.type, Manuscript.details) %>%
  kable(table.dt, format="latex", align='cllll', longtable=TRUE, escape=FALSE, col.names=hdr) %>%
  kable_styling(latex_options = c("hold_position"), full_width = FALSE) %>%
  row_spec(0, bold = TRUE, font_size = 12) %>%
  column_spec(1, width = "2.5em", bold = TRUE, border_left = TRUE) %>%
  column_spec(2, width = "20em") %>%
  column_spec(3, width = "13em") %>%
  column_spec(4, width = "34em", border_right = TRUE) 
# %>%
# GRRRRRRRRRRRRRRRRRRRR
#  pack_rows("Recruitment phase", hline_after = TRUE, 1) %>%
#  pack_rows("Beginning of the first NF/BCI training session", 2, hline_after = TRUE) %>%
#  pack_rows("Beginning of each NF/BCI session", 3, hline_before = TRUE) %>%
#  pack_rows("During NF/BCI sessions", 4) %>%
#  pack_rows("End of the last NF/BCI session", 5) %>%
#  pack_rows("Additional phase", 6)

```